# Generated by Django 3.1.10 on 2021-05-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210515_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True, verbose_name='статус публикации поста'),
            preserve_default=False,
        ),
    ]
