# Generated by Django 3.1.10 on 2021-05-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='insta_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='статус инсты'),
        ),
    ]
