# Generated by Django 3.1.10 on 2021-05-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordtoken',
            name='validity_status',
            field=models.BooleanField(default=True, verbose_name='статус токена'),
        ),
    ]
