# Generated by Django 3.1.10 on 2021-05-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordtoken_validity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordtoken',
            name='hash_password',
            field=models.CharField(default=1234, max_length=250, verbose_name='пароль'),
            preserve_default=False,
        ),
    ]
