# Generated by Django 3.1.10 on 2021-06-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_passwordtoken_hash_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='files_from_users', verbose_name='файл'),
        ),
    ]
